# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aram Davtyan
name: Aram Davtyan
position: Ph.D. Student 
email: aram.davtyan@unibe.ch
description: >-
  I am a Ph.D. student in the [Computer Vision Group](https://cvg.unibe.ch) at the [University of Bern](https://unibe.ch), supervised by [Prof. Dr. Paolo Favaro](https://cvg.unibe.ch/people/favaro). 
  I received my Specialist degree in Fundamental Mathematics and Mechanics at the [Lomonosov Moscow State University](https://msu.ru/en/) in 2020. 
  I also graduated from the [Yandex School of Data Analysis](https://dataschool.yandex.com/) in 2018. My topics of interest include Machine Learning, Computer Vision, Deep Learning and Generative Modeling.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://araachie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AraachieA
github_username: Araachie
google_scholar: 5YfxOK4AAAAJ
last_updated: December 23, 2024

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
